[package]
name = "s3-algo"
description = "High-performance algorithms for batch operations to Amazon S3"
version = "0.1.5"
authors = ["Erlend Langseth <3rlendhl@gmail.com>"]
license = "MIT"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = {version = "0.3.1", features = ["compat"]}
futures01 = {version = "0.1.29", package = "futures"}
futures-stopwatch = "0.3.0"
futures-retry = {git = "https://gitlab.com/mexus/futures-retry.git", rev="d3ba6a"}
rusoto_s3 = "0.43.0-beta.1"
rusoto_core = "0.43.0-beta.1"
tokio = {version = "0.2.9", features = ["time", "fs", "macros", "rt-threaded"]}
tokio-util = {version = "0.2.0", features = ["codec"]}
bytes05 = {version = "0.5.3", package = "bytes"}
bytes04 = {version = "0.4.12", package = "bytes"}
serde = {optional = true, version = "1.0", features = ["derive"]}
snafu = {version = "0.6.1", features = ["futures"]}

[dev-dependencies]
tempdir = "0.3.7"
multi-default-trait-impl = "0.1.2"
rand = "0.7.0"
walkdir = "2.2.9"
clap = "2.33.0"
tokio-compat = {version = "0.1.4", features = ["rt-current-thread"]}

[features]
default = ["serde1"]
serde1 = ["serde"]
