[package]
name = "s3-upload"
description = "Algorithm for uploading multiple files to AWS"
version = "0.1.0"
authors = ["Erlend Langseth <3rlendhl@gmail.com>"]
license = "MIT"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.1.25"
futures-stopwatch = "0.1.0"
futures-retry = {git = "https://gitlab.com/Ploppz/futures-retry.git"}
rusoto_s3 = "0.41.0"
rusoto_core = "0.41.0"
tokio = "0.1.22"
bytes = "0.4.12"
serde = {optional = true, version = "1.0", features = ["derive"]}
snafu = {version = "0.6.0", features = ["futures-01"] }

[dev-dependencies]
tempdir = "0.3.7"
multi-default-trait-impl = "0.1.2"
rand = "0.7.0"
walkdir = "2.2.9"
clap = "2.33.0"

[features]
default = ["serde1"]
serde1 = ["serde"]
